name: Publish v2.0.6 on Feb 1

on:
  schedule:
    # Runs at 00:00 UTC on 1 February
    - cron: '0 0 1 2 *'

permissions:
  contents: write

jobs:
  release-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish v2.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_YEAR=$(date +'%Y')
          
          # Safety check to ensure this only runs in 2026
          if [ "$CURRENT_YEAR" != "2026" ]; then
            echo "Skipping: This workflow is specific to the 2026 release."
            exit 0
          fi

          # Publishes the specific draft
          gh release edit v2.0.6 --draft=false
